version: '3'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt' # Монтирование всех сертификатов
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./tg-web-app-bot
    ports:
      - '3001:3001'
    networks:
      - dev

  frontend:
    build:
      context: ./tg-web-app-front
    ports:
      - '3000:3000'
    networks:
      - dev
